const questionBank = [
    { track: "selenium", type: "mcq", topic: "SELENIUM", question: "Which statement best explains the difference between findElement() and findElements()?", options: ["Both return a list, but one is faster", "findElement returns the first match; findElements returns a list and can be empty", "findElements throws when no element is found", "findElement only works with CSS selectors"], answer: 1, explanation: "findElement returns one WebElement and throws NoSuchElementException if there is no match. findElements returns a List<WebElement>; an empty list is the no-match result.", anchor: "Infosys Selenium Q7 / Deloitte R1 Q8" },
    { track: "selenium", type: "mcq", topic: "SELENIUM", question: "A checkout button appears after an API call finishes. What is the strongest default wait strategy?", options: ["Thread.sleep(10_000)", "A long implicit wait everywhere", "An explicit wait for the button to be clickable", "Refresh the page until it appears"], answer: 2, explanation: "Use a condition tied to the behavior you need: WebDriverWait.until(elementToBeClickable(...)). It communicates intent and avoids paying a fixed delay when the app is faster.", anchor: "Infosys Selenium Q8-10 / Deloitte R1 Q9" },
    { track: "selenium", type: "mcq", topic: "SELENIUM", question: "Which Selenium call reads the current value typed into an input box?", options: ["getText()", "getAttribute(\"value\")", "getCssValue(\"text\")", "getInputText()"], answer: 1, explanation: "Inputs render their current content as the value attribute, so getAttribute(\"value\") is the reliable choice. getText() often returns an empty string for input controls.", anchor: "Deloitte R1 Q11" },
    { track: "selenium", type: "mcq", topic: "SELENIUM", question: "What is the correct response when an interviewer asks if Selenium can automate a CAPTCHA?", options: ["Yes, with JavaScriptExecutor", "Yes, by polling until it solves", "No; CAPTCHA is designed to distinguish humans from automation", "Only in headless mode"], answer: 2, explanation: "Say no. The right testing approach is to disable or bypass CAPTCHA in a controlled test environment, or use a test hook—not defeat the security control in production.", anchor: "Infosys Selenium Q25 / Deloitte R2 Q16" },
    { track: "selenium", type: "mcq", topic: "SELENIUM", question: "What is the practical difference between driver.close() and driver.quit()?", options: ["close quits every browser; quit closes one tab", "close closes the current window; quit ends the whole WebDriver session", "They are aliases", "quit only works in headless mode"], answer: 1, explanation: "close() closes the current window or tab. quit() closes every window and ends the session, releasing the driver process.", anchor: "Infosys Selenium Q21" },
    { track: "selenium", type: "mcq", topic: "SELENIUM", question: "You need to type into a JavaScript prompt alert. Which sequence is correct?", options: ["driver.switchTo().alert().sendKeys(\"text\").accept()", "driver.alert().type(\"text\").close()", "driver.switchTo().window(\"alert\").sendKeys(\"text\")", "driver.findElement(Alert.prompt()).sendKeys(\"text\")"], answer: 0, explanation: "Switch to the alert, send keys to the prompt, then accept it: driver.switchTo().alert().sendKeys(\"text\").accept().", anchor: "Deloitte R1 Q12" },
    { track: "selenium", type: "mcq", topic: "SELENIUM", question: "What does a StaleElementReferenceException usually tell you?", options: ["The locator syntax is invalid", "The browser is offline", "The DOM changed and the stored element reference is no longer valid", "The element is hidden by CSS"], answer: 2, explanation: "The WebElement reference was tied to an older DOM. Re-locate the element after the update, and fix the synchronization point that allowed the stale reference.", anchor: "Infosys Selenium Q14" },
    { track: "selenium", type: "written", topic: "SELENIUM", question: "Explain how you would make a dynamic-element test reliable without using Thread.sleep().", coach: "Cover the condition, the locator, the timeout boundary, and what you would investigate if it still failed.", model: "I would use an explicit WebDriverWait with a stable locator and a condition that matches the next action—for example, wait until the element is visible or clickable. I would keep the timeout local to that behavior, avoid mixing arbitrary sleeps with implicit waits, and investigate the network or DOM state if the condition times out." },
    { track: "java", type: "mcq", topic: "JAVA", question: "Which collection preserves insertion order while using key/value pairs?", options: ["HashMap", "TreeMap", "LinkedHashMap", "Hashtable only"], answer: 2, explanation: "LinkedHashMap maintains a linked list through its entries, so iteration follows insertion order while retaining map semantics.", anchor: "Deloitte R1 Q5" },
    { track: "java", type: "mcq", topic: "JAVA", question: "Which is the best short explanation of method overloading?", options: ["Same method signature, different class", "Same method name with different parameter lists", "Changing a private method at runtime", "Replacing a parent method with a field"], answer: 1, explanation: "Overloading is compile-time polymorphism: same method name, different parameter list. Overriding is a subclass providing a new implementation for the same signature.", anchor: "Infosys Java Q14 / Deloitte R2 Q10" },
    { track: "java", type: "mcq", topic: "JAVA", question: "Which statement about checked exceptions is accurate?", options: ["They are ignored by the compiler", "They must be caught or declared", "They only happen during compilation", "They are the same as Errors"], answer: 1, explanation: "Checked exceptions are verified by the compiler, so code must handle them with catch or declare them with throws. RuntimeException subclasses are unchecked.", anchor: "Infosys Java Q10 / Deloitte R1 Q13" },
    { track: "java", type: "mcq", topic: "JAVA", question: "What is the main reason StringBuilder is preferred for repeated string concatenation in a loop?", options: ["It is immutable", "It avoids creating a new String object for every append", "It automatically sorts characters", "It is thread-safe by default"], answer: 1, explanation: "String is immutable, so repeated concatenation can create many intermediate objects. StringBuilder mutates a character buffer and is the usual single-threaded choice.", anchor: "Infosys Java Q12" },
    { track: "java", type: "mcq", topic: "JAVA", question: "What is the safest first move when asked to reverse a string while preserving whitespace positions?", options: ["Reverse the entire string with StringBuilder.reverse()", "Collect non-whitespace characters, reverse them, then place them back into non-whitespace positions", "Remove all spaces and return the result", "Sort the characters alphabetically"], answer: 1, explanation: "Separate the concerns: preserve the positions where whitespace occurs, reverse only the letters, then rebuild. This is easier to explain and test than trying to patch a reversed string.", anchor: "Deloitte R1 Q2" },
    { track: "java", type: "written", topic: "JAVA", question: "Explain the difference between an exception and an error, then give one example of each.", coach: "Keep it interview-sized: what the JVM means, whether application code normally recovers, and your examples.", model: "An exception is an event an application may handle or communicate, such as IOException or IllegalArgumentException. An Error signals a serious JVM or environment problem, such as OutOfMemoryError; application code generally should not try to recover from it." },
    { track: "framework", type: "mcq", topic: "FRAMEWORK", question: "What should a Page Object primarily own?", options: ["Business assertions for every test", "Locators and user-facing actions for a page structure", "The Maven build file", "All test data for the company"], answer: 1, explanation: "A Page Object hides locator and interaction details behind meaningful actions. Tests should describe behavior and assertions; page objects should model structure and interactions.", anchor: "Infosys Framework Q7 / repo STUDY_GUIDE" },
    { track: "framework", type: "mcq", topic: "FRAMEWORK", question: "If a product has 100 pages, do you automatically create 100 Page Objects?", options: ["Yes, one class per URL is mandatory", "No; model distinct structures and extract reusable components", "No; put every locator in one giant class", "Only if every page has a unique title"], answer: 1, explanation: "Page objects model distinct page structures, not URLs. Shared headers, grids, and templated page layouts can be reusable component or page classes.", anchor: "Deloitte R2 Q2" },
    { track: "framework", type: "mcq", topic: "FRAMEWORK", question: "Which answer best describes a data-driven framework?", options: ["Test logic is generated from random data only", "Test data is separated from test logic so the same flow can run with multiple datasets", "All tests are written in a spreadsheet", "Tests only run against databases"], answer: 1, explanation: "Data-driven design keeps inputs and expected results separate from the test flow, enabling multiple scenarios through a DataProvider, CSV, JSON, database, or similar source.", anchor: "Infosys Framework Q5 / Q8" },
    { track: "framework", type: "mcq", topic: "FRAMEWORK", question: "What is the strongest response when asked to explain your SampleSelenium framework?", options: ["It has many tests and runs in Chrome", "It is Maven + Java 17 + Selenium 4 with POM, explicit waits, ThreadLocal driver lifecycle, JUnit/TestNG/Cucumber drills, and CI", "It uses only manual test cases", "It is a collection of copied scripts"], answer: 1, explanation: "Lead with architecture, then the reason behind each choice: Page Objects reduce locator coupling, explicit waits synchronize behavior, and ThreadLocal supports parallel execution.", anchor: "Repo STUDY_GUIDE: Explain Your Framework" },
    { track: "framework", type: "written", topic: "FRAMEWORK", question: "Give your 60-second answer for: Explain your automation framework.", coach: "Use this order: build tool/language → POM → waits → driver lifecycle → data/BDD → reporting/CI. Name why, not just what.", model: "It is a Maven project using Java 17 and Selenium 4. Page Objects hold locators and actions, with BasePage helpers centralizing explicit waits so tests avoid Thread.sleep. DriverManager owns a ThreadLocal WebDriver, which keeps parallel tests isolated. The suite also has TestNG data-driven drills, Cucumber features for business-readable flows, failure screenshots, and CI through GitHub Actions/Jenkins." },
    { track: "testng-sql", type: "mcq", topic: "TESTNG", question: "What does a TestNG DataProvider give you?", options: ["A browser binary", "A way to run the same test with multiple data sets", "A replacement for assertions", "A report server"], answer: 1, explanation: "A DataProvider supplies parameters to a test method, making the scenario reusable across valid, invalid, boundary, or role-based inputs.", anchor: "Infosys TestNG Q6" },
    { track: "testng-sql", type: "mcq", topic: "TESTNG", question: "What is the practical difference between Assert and Verify?", options: ["Assert stops the current flow on failure; verify-style soft assertions collect failures before asserting", "Assert only works for APIs", "Verify always stops immediately", "There is no difference in any framework"], answer: 0, explanation: "A hard assertion fails fast. A soft assertion can collect multiple failures, but you must call assertAll() or the failures may never be reported.", anchor: "Infosys TestNG Q10" },
    { track: "testng-sql", type: "mcq", topic: "SQL", question: "Which query pattern is a standard way to find the second-highest distinct salary?", options: ["SELECT MAX(salary) FROM employees", "SELECT MAX(salary) FROM employees WHERE salary < (SELECT MAX(salary) FROM employees)", "SELECT salary FROM employees ORDER BY salary", "SELECT SECOND(salary) FROM employees"], answer: 1, explanation: "The inner MAX finds the highest salary; the outer query finds the greatest salary below it. Add DISTINCT or adapt the query when duplicates matter.", anchor: "Deloitte R1 Q3 / Infosys SQL Q8" },
    { track: "testng-sql", type: "mcq", topic: "SQL", question: "Which clause filters grouped results after aggregation?", options: ["WHERE", "ORDER BY", "HAVING", "GROUP"], answer: 2, explanation: "WHERE filters rows before grouping. HAVING filters groups after aggregate calculations such as COUNT or SUM.", anchor: "Infosys SQL Q6-7" },
    { track: "testng-sql", type: "mcq", topic: "TESTNG", question: "Why does a ThreadLocal WebDriver help parallel tests?", options: ["It makes the browser faster", "It gives each test thread its own driver reference", "It removes the need for waits", "It runs all tests in one browser"], answer: 1, explanation: "Each thread gets an isolated WebDriver value, preventing one parallel test from switching or quitting another test's browser.", anchor: "Repo STUDY_GUIDE: parallel execution" },
    { track: "interview", type: "mcq", topic: "VOICE", question: "A developer disagrees that a bug should be fixed. What is the most senior first response?", options: ["Escalate immediately without discussion", "Reproduce it, align on expected behavior and impact, then document the evidence and involve the right owner", "Close the bug to preserve velocity", "Argue until the developer agrees"], answer: 1, explanation: "Keep it evidence-first and collaborative: show the reproduction, expected versus actual behavior, risk, and agreed next action. Escalate when the decision or risk needs a higher owner.", anchor: "Deloitte R2 Q14" },
    { track: "interview", type: "mcq", topic: "VOICE", question: "Which three-part structure makes a technical interview answer easiest to follow?", options: ["Definition → example → trade-off", "Jargon → history → apology", "Code → silence → code", "Opinion → opinion → opinion"], answer: 0, explanation: "Start with the crisp definition, ground it in a real example, then show judgment by naming a trade-off or failure mode. This keeps an answer short without sounding shallow.", anchor: "Daily answer protocol" },
    { track: "interview", type: "mcq", topic: "VOICE", question: "When you forget the exact Java method name during a live coding prompt, what is the strongest move?", options: ["Stop speaking until you remember", "Say the pattern and intent, state you would verify the exact API, and keep working", "Invent a method name confidently", "Change the problem"], answer: 1, explanation: "Interviewers are evaluating reasoning as well as syntax. Narrate the invariant, data structure, and edge cases while being honest about the exact method name.", anchor: "Repo STUDY_GUIDE: Live-Interview Reminders" },
    { track: "interview", type: "written", topic: "VOICE", question: "How would you answer: Tell me about yourself and your QA responsibilities in 90 seconds?", coach: "Connect your experience to this role: automation scope, validation depth, framework ownership, and the value you create.", model: "I am a QA/SDET professional focused on turning risk into repeatable validation. My work spans UI automation with Selenium, API and data checks, framework patterns, and CI feedback. I focus on reliable signals—stable locators, meaningful waits, clear assertions, and evidence when a failure is real. In this role I would bring that same approach to expanding coverage while keeping the suite maintainable and useful to the team." }
];

const codingDrills = [
    { category: "LABCORP-STYLE", title: "Print every letter of a name", prompt: "Given a name, write Java code that visits and prints each letter in order. Start with the input \"PETER\" and make the solution work for any name.", listening: "a loop, charAt or a character array, and a clear explanation of the index boundary", hint: "A String has a length and a zero-based character at each index.", solution: "String name = \"PETER\";\nfor (int i = 0; i < name.length(); i++) {\n    System.out.println(name.charAt(i));\n}" },
    { category: "DELOITTE-STYLE", title: "Reverse letters, preserve whitespace", prompt: "Write Java code to reverse the non-whitespace characters in a string while keeping every whitespace character in its original position. Example: \"a b c\" → \"c b a\".", listening: "separating whitespace from content, preserving positions, and calling out an empty or all-whitespace case", hint: "First collect non-whitespace characters. Walk the original string again and replace only non-whitespace positions from the reversed collection.", solution: "String input = \"a b c\";\nStringBuilder letters = new StringBuilder();\nfor (char c : input.toCharArray()) {\n    if (!Character.isWhitespace(c)) letters.append(c);\n}\nletters.reverse();\nStringBuilder result = new StringBuilder();\nint index = 0;\nfor (char c : input.toCharArray()) {\n    result.append(Character.isWhitespace(c) ? c : letters.charAt(index++));\n}\nSystem.out.println(result);" },
    { category: "JAVA CORE", title: "Find duplicate characters", prompt: "Given a string, print each character that appears more than once. Explain whether you want to print a duplicate once or every repeated occurrence.", listening: "a Set or Map, an explicit policy for output, and case-sensitivity as a stated assumption", hint: "A frequency map answers how many times each character occurs. A LinkedHashMap can preserve first-seen order.", solution: "String input = \"selenium\";\nMap<Character, Integer> counts = new LinkedHashMap<>();\nfor (char c : input.toCharArray()) {\n    counts.put(c, counts.getOrDefault(c, 0) + 1);\n}\ncounts.forEach((character, count) -> {\n    if (count > 1) System.out.println(character);\n});" },
    { category: "JAVA CORE", title: "Check for a palindrome", prompt: "Write a method that returns true when a string reads the same forward and backward. State whether you ignore case or whitespace.", listening: "normalization assumptions, two-pointer logic or a reversed comparison, and a useful edge case", hint: "Compare the first and last characters, then move both pointers toward the middle.", solution: "static boolean isPalindrome(String value) {\n    String input = value.replaceAll(\"\\\\s+\", \"\").toLowerCase();\n    int left = 0, right = input.length() - 1;\n    while (left < right) {\n        if (input.charAt(left++) != input.charAt(right--)) return false;\n    }\n    return true;\n}" },
    { category: "DELOITTE-STYLE", title: "Find the second-largest salary", prompt: "Write a SQL query that returns the second-largest distinct salary from an employee table. Explain what happens if there is no second value.", listening: "distinctness, a clear subquery or ranking approach, and the empty-result edge case", hint: "Find the maximum salary below the overall maximum salary.", solution: "SELECT MAX(salary) AS second_highest\nFROM employees\nWHERE salary < (SELECT MAX(salary) FROM employees);" },
    { category: "JAVA CORE", title: "Reverse a string", prompt: "Write a Java method to reverse a string without changing the original input object. Mention the simplest library-backed solution and how you would do it manually.", listening: "String immutability, StringBuilder, and one sentence about a two-pointer or loop alternative", hint: "StringBuilder has a reverse operation and returns a new String when you call toString().", solution: "static String reverse(String input) {\n    return new StringBuilder(input).reverse().toString();\n}" }
];

const state = { track: "all", questions: [], index: 0, correct: 0, answered: false, selected: null, codingIndex: 0 };
const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => Array.from(document.querySelectorAll(selector));

function shuffle(items) { return [...items].sort(() => Math.random() - 0.5); }
function todayKey() { return new Date().toISOString().slice(0, 10); }
function readStats() {
    try { return JSON.parse(localStorage.getItem("sdetFieldTestStats")) || { streak: 0, best: null, sessions: 0, lastDate: null }; }
    catch { return { streak: 0, best: null, sessions: 0, lastDate: null }; }
}
function writeStats(stats) { localStorage.setItem("sdetFieldTestStats", JSON.stringify(stats)); }
function renderStats() {
    const stats = readStats();
    $("#streak-stat").textContent = (stats.streak || 0) + " day" + (stats.streak === 1 ? "" : "s");
    $("#best-stat").textContent = stats.best === null ? "—" : stats.best + "/10";
    $("#sessions-stat").textContent = stats.sessions || 0;
}
function updateTrackLabel() {
    const button = document.querySelector("[data-track=\"" + state.track + "\"]");
    $("#track-label").textContent = (state.track === "all" ? "MIXED SIGNAL" : button.textContent.replace("↗", "").trim()).toUpperCase();
}
function startSession() {
    const pool = state.track === "all" ? questionBank : questionBank.filter((item) => item.track === state.track);
    let selected = shuffle(pool);
    while (selected.length < 10) selected = selected.concat(shuffle(pool));
    state.questions = selected.slice(0, 10);
    state.index = 0; state.correct = 0; state.answered = false; state.selected = null;
    updateTrackLabel(); renderQuestion();
}
function renderQuestion() {
    const question = state.questions[state.index];
    if (!question) return showComplete();
    state.answered = false; state.selected = null;
    const current = state.index + 1;
    $("#question-count").textContent = "QUESTION " + String(current).padStart(2, "0") + " / " + state.questions.length;
    $("#question-topic").textContent = question.topic;
    $("#progress-fill").style.width = (current / state.questions.length) * 100 + "%";
    const title = "<h3><span class=\"q-number\">" + (question.type === "written" ? "WRITE YOUR ANSWER" : "CHOOSE THE BEST ANSWER") + "</span>" + question.question + "</h3>";
    const view = $("#question-view");
    if (question.type === "written") {
        view.innerHTML = "<div class=\"question-frame written\">" + title + "<textarea class=\"written-answer\" id=\"written-answer\" placeholder=\"Say it out loud first, then capture your answer here...\"></textarea><p class=\"coach-prompt\">" + question.coach + "</p><div class=\"question-foot\"><span></span><div class=\"question-actions\"><button class=\"text-button\" id=\"reveal-written\" type=\"button\">Reveal coach note <span>↗</span></button><button class=\"button button-primary\" id=\"next-question\" type=\"button\" disabled>Log answer <span>→</span></button></div></div><div id=\"written-feedback\"></div></div>";
        $("#written-answer").addEventListener("input", (event) => { $("#next-question").disabled = !event.target.value.trim(); });
        $("#reveal-written").addEventListener("click", () => { $("#written-feedback").innerHTML = "<div class=\"feedback\"><strong>Coach note:</strong> " + question.model + "</div>"; });
    } else {
        const options = question.options.map((option, index) => "<button class=\"option\" data-option=\"" + index + "\" type=\"button\"><span class=\"option-letter\">" + String.fromCharCode(65 + index) + "</span><span>" + option + "</span></button>").join("");
        view.innerHTML = "<div class=\"question-frame\">" + title + "<div class=\"answer-options\">" + options + "</div><div class=\"question-foot\"><span class=\"anchor-note\">Source signal: " + question.anchor + "</span><div class=\"question-actions\"><button class=\"text-button\" id=\"skip-question\" type=\"button\">Skip for now</button><button class=\"button button-primary\" id=\"check-answer\" type=\"button\" disabled>Check answer <span>→</span></button></div></div><div id=\"answer-feedback\"></div></div>";
        $$(".option").forEach((button) => button.addEventListener("click", () => {
            if (state.answered) return;
            state.selected = Number(button.dataset.option);
            $$(".option").forEach((candidate) => candidate.classList.toggle("selected", candidate === button));
            $("#check-answer").disabled = false;
        }));
        $("#check-answer").addEventListener("click", checkAnswer);
        $("#skip-question").addEventListener("click", () => { state.index += 1; renderQuestion(); });
    }
}
function checkAnswer() {
    if (state.selected === null || state.answered) return;
    const question = state.questions[state.index];
    state.answered = true;
    const correct = state.selected === question.answer;
    if (correct) state.correct += 1;
    $$(".option").forEach((button, index) => {
        button.disabled = true;
        if (index === question.answer) button.classList.add("correct");
        if (index === state.selected && !correct) button.classList.add("incorrect");
    });
    $("#answer-feedback").innerHTML = "<div class=\"feedback " + (correct ? "is-correct" : "") + "\"><strong>" + (correct ? "Correct." : "Not quite.") + "</strong> " + question.explanation + "</div><div class=\"question-actions next-action\"><button class=\"button button-primary\" id=\"next-question\" type=\"button\">" + (state.index === state.questions.length - 1 ? "See score" : "Next question") + " <span>→</span></button></div>";
    $("#check-answer").remove(); $("#skip-question").remove();
    $("#next-question").addEventListener("click", () => { state.index += 1; renderQuestion(); });
}
function showComplete() {
    const stats = readStats(), score = state.correct, today = todayKey(), yesterday = new Date(Date.now() - 86400000).toISOString().slice(0, 10);
    stats.streak = stats.lastDate === yesterday ? (stats.streak || 0) + 1 : stats.lastDate === today ? (stats.streak || 1) : 1;
    stats.lastDate = today; stats.sessions = (stats.sessions || 0) + 1; stats.best = stats.best === null ? score : Math.max(stats.best, score); writeStats(stats); renderStats();
    $("#question-count").textContent = "SESSION COMPLETE"; $("#question-topic").textContent = "LOGGED"; $("#progress-fill").style.width = "100%";
    $("#question-view").innerHTML = "<div class=\"complete-state\"><div class=\"score-stamp\">" + score + "/" + state.questions.length + "</div><h3>You showed up.<br><em>Now sharpen the misses.</em></h3><p>Review the answer notes, then run the same track again tomorrow. Your job is not to recognize the answer—it is to produce it cleanly under pressure.</p><div><button class=\"button button-primary\" id=\"restart-session\" type=\"button\">Run another session <span>↗</span></button></div></div>";
    $("#restart-session").addEventListener("click", startSession);
}
function renderCoding() {
    const drill = codingDrills[state.codingIndex];
    $("#coding-category").textContent = drill.category; $("#coding-number").textContent = "DRILL " + String(state.codingIndex + 1).padStart(2, "0");
    $("#coding-title").textContent = drill.title; $("#coding-prompt-text").textContent = drill.prompt; $("#coding-listening").textContent = drill.listening;
    $("#code-answer").value = ""; $("#hint-box").hidden = true; $("#solution-box").hidden = true; $("#hint-box").textContent = drill.hint; $("#solution-box").textContent = drill.solution;
}
$$(".track-button").forEach((button) => button.addEventListener("click", () => {
    state.track = button.dataset.track; $$(".track-button").forEach((item) => item.classList.toggle("is-active", item === button)); startSession();
}));
$("#new-session").addEventListener("click", startSession);
$("#next-coding").addEventListener("click", () => { state.codingIndex = (state.codingIndex + 1) % codingDrills.length; renderCoding(); });
$("#show-hint").addEventListener("click", () => { $("#hint-box").hidden = !$("#hint-box").hidden; });
$("#show-solution").addEventListener("click", () => { $("#solution-box").hidden = !$("#solution-box").hidden; });
$("#date-readout").textContent = new Intl.DateTimeFormat("en-US", { weekday: "short", month: "short", day: "numeric", year: "numeric" }).format(new Date());
renderStats(); renderCoding(); startSession();
