const questionBank = [
    { track: "selenium", type: "mcq", topic: "SELENIUM", question: "Which statement best explains the difference between findElement() and findElements()?", options: ["Both return a list, but one is faster", "findElement returns the first match; findElements returns a list and can be empty", "findElements throws when no element is found", "findElement only works with CSS selectors"], answer: 1, explanation: "findElement returns one WebElement and throws NoSuchElementException if there is no match. findElements returns a List<WebElement>; an empty list is the no-match result.", anchor: "Infosys Selenium Q7 / Deloitte R1 Q8" },
    { track: "selenium", type: "mcq", topic: "SELENIUM", question: "A checkout button appears after an API call finishes. What is the strongest default wait strategy?", options: ["Thread.sleep(10_000)", "A long implicit wait everywhere", "An explicit wait for the button to be clickable", "Refresh the page until it appears"], answer: 2, explanation: "Use a condition tied to the behavior you need: WebDriverWait.until(elementToBeClickable(...)). It communicates intent and avoids paying a fixed delay when the app is faster.", anchor: "Infosys Selenium Q8-10 / Deloitte R1 Q9" },
    { track: "selenium", type: "mcq", topic: "SELENIUM", question: "Which Selenium call reads the current value typed into an input box?", options: ["getText()", "getAttribute(\"value\")", "getCssValue(\"text\")", "getInputText()"], answer: 1, explanation: "Inputs render their current content as the value attribute, so getAttribute(\"value\") is the reliable choice. getText() often returns an empty string for input controls.", anchor: "Deloitte R1 Q11" },
    { track: "selenium", type: "mcq", topic: "SELENIUM", question: "What is the correct response when an interviewer asks if Selenium can automate a CAPTCHA?", options: ["Yes, with JavaScriptExecutor", "Yes, by polling until it solves", "No; CAPTCHA is designed to distinguish humans from automation", "Only in headless mode"], answer: 2, explanation: "Say no. The right testing approach is to disable or bypass CAPTCHA in a controlled test environment, or use a test hook—not defeat the security control in production.", anchor: "Infosys Selenium Q25 / Deloitte R2 Q16" },
    { track: "selenium", type: "mcq", topic: "SELENIUM", question: "What is the practical difference between driver.close() and driver.quit()?", options: ["close quits every browser; quit closes one tab", "close closes the current window; quit ends the whole WebDriver session", "They are aliases", "quit only works in headless mode"], answer: 1, explanation: "close() closes the current window or tab. quit() closes every window and ends the session, releasing the driver process.", anchor: "Infosys Selenium Q21" },
    { track: "selenium", type: "mcq", topic: "SELENIUM", question: "You need to type into a JavaScript prompt alert. Which sequence is correct?", options: ["driver.switchTo().alert().sendKeys(\"text\").accept()", "driver.alert().type(\"text\").close()", "driver.switchTo().window(\"alert\").sendKeys(\"text\")", "driver.findElement(Alert.prompt()).sendKeys(\"text\")"], answer: 0, explanation: "Switch to the alert, send keys to the prompt, then accept it: driver.switchTo().alert().sendKeys(\"text\").accept().", anchor: "Deloitte R1 Q12" },
    { track: "selenium", type: "mcq", topic: "SELENIUM", question: "What does a StaleElementReferenceException usually tell you?", options: ["The locator syntax is invalid", "The browser is offline", "The DOM changed and the stored element reference is no longer valid", "The element is hidden by CSS"], answer: 2, explanation: "The WebElement reference was tied to an older DOM. Re-locate the element after the update, and fix the synchronization point that allowed the stale reference.", anchor: "Infosys Selenium Q14" },
    { track: "selenium", type: "written", topic: "SELENIUM", question: "How do you handle flaky Selenium tests? Walk through your diagnosis and fixes.", coach: "Name the top causes (synchronization, test data, environment, order dependence), your diagnosis steps, and why blind retries are a last resort.", model: "First I prove it is actually flaky: run it in isolation and in the suite, and read the failure artifacts—screenshot, DOM, logs. The usual root cause is synchronization, fixed with an explicit wait on the right condition instead of sleeps. Next suspects are shared test data, order dependence, and environment differences like headless vs headed viewport size. I fix the root cause rather than wrapping retries around it—retry logic hides real intermittent product bugs. A quarantine tag keeps a flaky test out of the signal while it is being fixed, so the team keeps trusting a red build.", anchor: "Luxoft high-probability Q11" },
    { track: "selenium", type: "written", topic: "SELENIUM", question: "Explain how you would make a dynamic-element test reliable without using Thread.sleep().", coach: "Cover the condition, the locator, the timeout boundary, and what you would investigate if it still failed.", model: "I would use an explicit WebDriverWait with a stable locator and a condition that matches the next action—for example, wait until the element is visible or clickable. I would keep the timeout local to that behavior, avoid mixing arbitrary sleeps with implicit waits, and investigate the network or DOM state if the condition times out." },
    { track: "java", type: "mcq", topic: "JAVA", question: "Which collection preserves insertion order while using key/value pairs?", options: ["HashMap", "TreeMap", "LinkedHashMap", "Hashtable only"], answer: 2, explanation: "LinkedHashMap maintains a linked list through its entries, so iteration follows insertion order while retaining map semantics.", anchor: "Deloitte R1 Q5" },
    { track: "java", type: "mcq", topic: "JAVA", question: "Which is the best short explanation of method overloading?", options: ["Same method signature, different class", "Same method name with different parameter lists", "Changing a private method at runtime", "Replacing a parent method with a field"], answer: 1, explanation: "Overloading is compile-time polymorphism: same method name, different parameter list. Overriding is a subclass providing a new implementation for the same signature.", anchor: "Infosys Java Q14 / Deloitte R2 Q10" },
    { track: "java", type: "mcq", topic: "JAVA", question: "Which statement about checked exceptions is accurate?", options: ["They are ignored by the compiler", "They must be caught or declared", "They only happen during compilation", "They are the same as Errors"], answer: 1, explanation: "Checked exceptions are verified by the compiler, so code must handle them with catch or declare them with throws. RuntimeException subclasses are unchecked.", anchor: "Infosys Java Q10 / Deloitte R1 Q13" },
    { track: "java", type: "mcq", topic: "JAVA", question: "What is the main reason StringBuilder is preferred for repeated string concatenation in a loop?", options: ["It is immutable", "It avoids creating a new String object for every append", "It automatically sorts characters", "It is thread-safe by default"], answer: 1, explanation: "String is immutable, so repeated concatenation can create many intermediate objects. StringBuilder mutates a character buffer and is the usual single-threaded choice.", anchor: "Infosys Java Q12" },
    { track: "java", type: "mcq", topic: "JAVA", question: "What is the safest first move when asked to reverse a string while preserving whitespace positions?", options: ["Reverse the entire string with StringBuilder.reverse()", "Collect non-whitespace characters, reverse them, then place them back into non-whitespace positions", "Remove all spaces and return the result", "Sort the characters alphabetically"], answer: 1, explanation: "Separate the concerns: preserve the positions where whitespace occurs, reverse only the letters, then rebuild. This is easier to explain and test than trying to patch a reversed string.", anchor: "Deloitte R1 Q2" },
    { track: "java", type: "written", topic: "JAVA", question: "Explain the difference between an exception and an error, then give one example of each.", coach: "Keep it interview-sized: what the JVM means, whether application code normally recovers, and your examples.", model: "An exception is an event an application may handle or communicate, such as IOException or IllegalArgumentException. An Error signals a serious JVM or environment problem, such as OutOfMemoryError; application code generally should not try to recover from it." },
    { track: "framework", type: "mcq", topic: "FRAMEWORK", question: "What should a Page Object primarily own?", options: ["Business assertions for every test", "Locators and user-facing actions for a page structure", "The Maven build file", "All test data for the company"], answer: 1, explanation: "A Page Object hides locator and interaction details behind meaningful actions. Tests should describe behavior and assertions; page objects should model structure and interactions.", anchor: "Infosys Framework Q7 / repo STUDY_GUIDE" },
    { track: "framework", type: "mcq", topic: "FRAMEWORK", question: "If a product has 100 pages, do you automatically create 100 Page Objects?", options: ["Yes, one class per URL is mandatory", "No; model distinct structures and extract reusable components", "No; put every locator in one giant class", "Only if every page has a unique title"], answer: 1, explanation: "Page objects model distinct page structures, not URLs. Shared headers, grids, and templated page layouts can be reusable component or page classes.", anchor: "Deloitte R2 Q2" },
    { track: "framework", type: "mcq", topic: "FRAMEWORK", question: "Which answer best describes a data-driven framework?", options: ["Test logic is generated from random data only", "Test data is separated from test logic so the same flow can run with multiple datasets", "All tests are written in a spreadsheet", "Tests only run against databases"], answer: 1, explanation: "Data-driven design keeps inputs and expected results separate from the test flow, enabling multiple scenarios through a DataProvider, CSV, JSON, database, or similar source.", anchor: "Infosys Framework Q5 / Q8" },
    { track: "framework", type: "mcq", topic: "FRAMEWORK", question: "What is the strongest response when asked to explain your SampleSelenium framework?", options: ["It has many tests and runs in Chrome", "It is Maven + Java 17 + Selenium 4 with POM, explicit waits, ThreadLocal driver lifecycle, JUnit/TestNG/Cucumber drills, and CI", "It uses only manual test cases", "It is a collection of copied scripts"], answer: 1, explanation: "Lead with architecture, then the reason behind each choice: Page Objects reduce locator coupling, explicit waits synchronize behavior, and ThreadLocal supports parallel execution.", anchor: "Repo STUDY_GUIDE: Explain Your Framework" },
    { track: "framework", type: "mcq", topic: "CUCUMBER", question: "In Cucumber, what is the relationship between a feature file, step definitions, and hooks?", options: ["Feature files contain Java code that runs directly", "Gherkin steps in the feature file are matched to annotated Java methods by expression; @Before/@After hooks run around each scenario", "Hooks replace step definitions", "Step definitions must live inside the feature file"], answer: 1, explanation: "The feature file is plain Gherkin (Given/When/Then). Cucumber matches each step to a Java method via cucumber expressions or regex. Hooks (@Before/@After) wrap every scenario—driver setup and teardown live there, not in the steps.", anchor: "Luxoft Q3 / repo Module 8" },
    { track: "framework", type: "mcq", topic: "CUCUMBER", question: "What do Cucumber tags and data tables give you?", options: ["Tags rename scenarios; data tables format the report", "Tags select which scenarios run (@smoke, @regression) and can scope hooks; data tables pass structured multi-row input into a single step", "Both are deprecated Gherkin features", "Tags only work in Jenkins"], answer: 1, explanation: "Tags filter execution (cucumber.filter.tags) and scope hooks like @Before(\"@api\"). A data table arrives in the step method as a DataTable or List<Map<String,String>>—the standard way to feed a step several rows of test data. Scenario Outline + Examples is the related repetition mechanism.", anchor: "Luxoft Q3 / repo Module 8" },
    { track: "framework", type: "mcq", topic: "FRAMEWORK", question: "Which design patterns show up in a typical Java automation framework, and where?", options: ["Only Page Object; nothing else applies", "Page Object for structure, Factory for driver creation, Singleton/ThreadLocal for driver lifecycle, Builder for test data or requests", "MVC everywhere", "Observer for locators"], answer: 1, explanation: "Be ready to point at your own code: Page Object reduces locator coupling, a Factory method creates the right WebDriver per browser, the ThreadLocal DriverManager is Singleton-like per thread, and Builder assembles test data or REST Assured request specs fluently.", anchor: "Luxoft Q10 / repo DriverManager" },
    { track: "framework", type: "mcq", topic: "FRAMEWORK", question: "A new feature ships next sprint. How do you decide what to automate first?", options: ["Automate everything immediately", "Automate whatever is easiest", "Prioritize by risk and repetition: critical business flows, calculation correctness, and stable repetitive regression paths; leave one-off exploratory checks manual", "Only automate UI tests"], answer: 2, explanation: "Highest value first: revenue-critical and calculation-heavy paths, then high-frequency regression. Prefer the API layer where possible—faster and more stable than UI. Volatile UIs and one-time checks are poor automation investments.", anchor: "Luxoft Q12" },
    { track: "framework", type: "mcq", topic: "CI/CD", question: "How does automation typically integrate with Jenkins, and how are results reported?", options: ["Jenkins runs tests manually on request only", "A pipeline stage runs mvn test (headless) on push/PR and nightly; surefire/cucumber reports and failure screenshots are published as artifacts, and the build gates on failures", "Jenkins replaces the test framework", "Results are emailed as raw console logs"], answer: 1, explanation: "The Jenkinsfile (or GitHub Actions) checks out the branch, runs the suite headless, publishes JUnit XML so trends show per-test history, archives screenshots/reports, and fails the build to block a broken merge. Same pipeline nightly for the full regression.", anchor: "Luxoft Q13 / repo Jenkinsfile" },
    { track: "framework", type: "written", topic: "FRAMEWORK", question: "Give your 60-second answer for: Explain your automation framework.", coach: "Use this order: build tool/language → POM → waits → driver lifecycle → data/BDD → reporting/CI. Name why, not just what.", model: "It is a Maven project using Java 17 and Selenium 4. Page Objects hold locators and actions, with BasePage helpers centralizing explicit waits so tests avoid Thread.sleep. DriverManager owns a ThreadLocal WebDriver, which keeps parallel tests isolated. The suite also has TestNG data-driven drills, Cucumber features for business-readable flows, failure screenshots, and CI through GitHub Actions/Jenkins." },
    { track: "testng-sql", type: "mcq", topic: "TESTNG", question: "What does a TestNG DataProvider give you?", options: ["A browser binary", "A way to run the same test with multiple data sets", "A replacement for assertions", "A report server"], answer: 1, explanation: "A DataProvider supplies parameters to a test method, making the scenario reusable across valid, invalid, boundary, or role-based inputs.", anchor: "Infosys TestNG Q6" },
    { track: "testng-sql", type: "mcq", topic: "TESTNG", question: "What is the practical difference between Assert and Verify?", options: ["Assert stops the current flow on failure; verify-style soft assertions collect failures before asserting", "Assert only works for APIs", "Verify always stops immediately", "There is no difference in any framework"], answer: 0, explanation: "A hard assertion fails fast. A soft assertion can collect multiple failures, but you must call assertAll() or the failures may never be reported.", anchor: "Infosys TestNG Q10" },
    { track: "testng-sql", type: "mcq", topic: "SQL", question: "Which query pattern is a standard way to find the second-highest distinct salary?", options: ["SELECT MAX(salary) FROM employees", "SELECT MAX(salary) FROM employees WHERE salary < (SELECT MAX(salary) FROM employees)", "SELECT salary FROM employees ORDER BY salary", "SELECT SECOND(salary) FROM employees"], answer: 1, explanation: "The inner MAX finds the highest salary; the outer query finds the greatest salary below it. Add DISTINCT or adapt the query when duplicates matter.", anchor: "Deloitte R1 Q3 / Infosys SQL Q8" },
    { track: "testng-sql", type: "mcq", topic: "SQL", question: "Which clause filters grouped results after aggregation?", options: ["WHERE", "ORDER BY", "HAVING", "GROUP"], answer: 2, explanation: "WHERE filters rows before grouping. HAVING filters groups after aggregate calculations such as COUNT or SUM.", anchor: "Infosys SQL Q6-7" },
    { track: "testng-sql", type: "mcq", topic: "TESTNG", question: "Why does a ThreadLocal WebDriver help parallel tests?", options: ["It makes the browser faster", "It gives each test thread its own driver reference", "It removes the need for waits", "It runs all tests in one browser"], answer: 1, explanation: "Each thread gets an isolated WebDriver value, preventing one parallel test from switching or quitting another test's browser.", anchor: "Repo STUDY_GUIDE: parallel execution" },
    { track: "testng-sql", type: "mcq", topic: "SQL", question: "How do you reconcile API results against database values?", options: ["Trust the API; the database is an implementation detail", "Query the source tables with SQL, compute the same expected values (aggregates, joins), and assert the API response matches row-by-row and in totals", "Compare row counts only", "Screenshot both and compare visually"], answer: 1, explanation: "Expected-vs-actual reconciliation: run the SQL that defines truth (joins, SUM/GROUP BY), then assert the API's fields and totals against it. Mismatches localize the defect—API layer, calculation service, or data. This is the SDET SQL story.", anchor: "Luxoft Q9 / repo Module 7" },
    { track: "testng-sql", type: "mcq", topic: "SQL", question: "What is SQL injection, and what do you verify as a tester?", options: ["A performance tuning technique", "Malicious input altering a query's structure; verify inputs like ' OR '1'='1 are rejected and that the code uses parameterized queries/prepared statements, not string concatenation", "A way to speed up joins", "A database backup strategy"], answer: 1, explanation: "Classic probe: a login field fed ' OR '1'='1 must not authenticate. The fix you verify in code review is parameterized queries (PreparedStatement / ORM bind variables)—user input must never be concatenated into SQL. Error messages should not leak schema details either.", anchor: "Luxoft interview reports" },
    { track: "interview", type: "mcq", topic: "VOICE", question: "A developer disagrees that a bug should be fixed. What is the most senior first response?", options: ["Escalate immediately without discussion", "Reproduce it, align on expected behavior and impact, then document the evidence and involve the right owner", "Close the bug to preserve velocity", "Argue until the developer agrees"], answer: 1, explanation: "Keep it evidence-first and collaborative: show the reproduction, expected versus actual behavior, risk, and agreed next action. Escalate when the decision or risk needs a higher owner.", anchor: "Deloitte R2 Q14" },
    { track: "interview", type: "mcq", topic: "VOICE", question: "Which three-part structure makes a technical interview answer easiest to follow?", options: ["Definition → example → trade-off", "Jargon → history → apology", "Code → silence → code", "Opinion → opinion → opinion"], answer: 0, explanation: "Start with the crisp definition, ground it in a real example, then show judgment by naming a trade-off or failure mode. This keeps an answer short without sounding shallow.", anchor: "Daily answer protocol" },
    { track: "interview", type: "mcq", topic: "VOICE", question: "When you forget the exact Java method name during a live coding prompt, what is the strongest move?", options: ["Stop speaking until you remember", "Say the pattern and intent, state you would verify the exact API, and keep working", "Invent a method name confidently", "Change the problem"], answer: 1, explanation: "Interviewers are evaluating reasoning as well as syntax. Narrate the invariant, data structure, and edge cases while being honest about the exact method name.", anchor: "Repo STUDY_GUIDE: Live-Interview Reminders" },
    { track: "api", type: "mcq", topic: "API", question: "A POST to /api/trades successfully creates a new trade. Which response is correct per REST semantics?", options: ["200 OK with the trade in the body", "201 Created with a Location header pointing at the new trade's URI", "204 No Content", "202 Accepted with no follow-up"], answer: 1, explanation: "201 means a new resource now exists because of this request, and it should carry a Location header with the new resource's URI. A POST-create that returns 200 is a defect worth filing—clients and gateways key off the semantics.", anchor: "Repo Module 9 / the 200-vs-201 question" },
    { track: "api", type: "mcq", topic: "API", question: "What is the difference between HTTP 401 and 403?", options: ["They are interchangeable auth errors", "401 means unauthenticated (who are you?); 403 means authenticated but forbidden (you may not)", "401 is a server error; 403 is a client error", "403 means the token expired; 401 means the endpoint moved"], answer: 1, explanation: "401 says credentials are missing or invalid—retrying WITH credentials can succeed. 403 says the server knows who you are and still refuses—retrying won't help. Test both: no token, and a valid token for the wrong role.", anchor: "Repo Module 9 / SourceD09ApiDrills" },
    { track: "api", type: "mcq", topic: "API", question: "Which HTTP methods are idempotent?", options: ["GET, PUT, DELETE — repeating them leaves the same end state", "POST and PUT only", "All of them", "None; HTTP has no idempotency concept"], answer: 0, explanation: "GET, PUT, and DELETE produce the same end state no matter how many times you repeat them. POST is NOT idempotent—each call can create another resource. Retry logic and test cleanup both depend on knowing this.", anchor: "Repo Module 9 / idempotency talk track" },
    { track: "api", type: "mcq", topic: "API", question: "A calculation engine queues a long-running valuation request instead of computing it inline. Which status fits the initial response?", options: ["200 OK with the final result", "201 Created", "202 Accepted, with a way to poll for the result", "504 Gateway Timeout"], answer: 2, explanation: "202 Accepted means the request was valid and queued for asynchronous processing—common in calc-intensive services. The test then polls a status endpoint or result URI until the computation completes.", anchor: "Repo Module 9 / status-code family" },
    { track: "api", type: "mcq", topic: "API", question: "In REST Assured, which chain correctly asserts a status code and a JSON field?", options: ["driver.get(url).assertStatus(200)", "given().when().get(\"/api/trades/1001\").then().statusCode(200).body(\"instrument\", equalTo(\"AAPL\"))", "restAssured.fetch(url).expect(200)", "new Response(url).jsonPath().assert(200)"], answer: 1, explanation: "The given/when/then DSL: given() sets up headers and body, when() makes the call, then() asserts status, headers, and body via Hamcrest matchers with GPath expressions like totals.grossMarketValue.", anchor: "Repo Module 9 / SourceD09ApiDrills" },
    { track: "api", type: "mcq", topic: "API", question: "How do you validate a large JSON response of financial calculations beyond spot-checking one field?", options: ["Assert the response is not null", "Compare the raw string to a saved copy", "Extract the arrays and recompute the math—each position's marketValue = quantity × price, and the reported total = the sum you recompute", "Check only the HTTP status code"], answer: 2, explanation: "Recompute the business math in the test: per-row derived values and the aggregate totals. String comparison breaks on field order and formatting; a null check proves nothing about correctness.", anchor: "Repo Module 9 / portfolioValuationJsonRecomputesToItsOwnTotals" },
    { track: "api", type: "mcq", topic: "API", question: "What is a POJO request model in Java API automation?", options: ["A browser page object used for UI locators", "A simple Java class representing the request body so a mapper can serialize it to JSON", "A database table that stores API requests", "A Cucumber feature file written in Java"], answer: 1, explanation: "A POJO request model gives the JSON body a typed Java representation. Jackson or REST Assured serializes the object into JSON, which is more reusable and maintainable than embedding raw JSON strings in every test.", anchor: "Luxoft API follow-up / d09_api" },
    { track: "api", type: "mcq", topic: "API", question: "How would you deserialize a JSON array response into TradeResult POJOs?", options: ["Use driver.findElements()", "Use ObjectMapper.readValue(json, new TypeReference<List<TradeResult>>() {}) or REST Assured extract().as(new TypeRef<List<TradeResult>>() {})", "Compare the raw JSON string with ==", "Convert the response to HTML first"], answer: 1, explanation: "Jackson maps the JSON fields into typed Java objects. With REST Assured, extract().as(new TypeRef<List<TradeResult>>() {}) gives a list of POJOs that can be used for field-level and business-rule assertions.", anchor: "Luxoft API follow-up / d09_api" },
    { track: "api", type: "mcq", topic: "SPRING BOOT", question: "What does @WebMvcTest with MockMvc give you when testing a Spring Boot controller?", options: ["A full application context with a real HTTP port", "A controller-slice test: only the web layer loads, services are mocked with @MockBean, no server socket needed", "A browser-based UI test", "A database integration test"], answer: 1, explanation: "@WebMvcTest loads only the web layer, so it is fast. mockMvc.perform(post(...)).andExpect(status().isCreated()) asserts status and JSON without starting a server. @SpringBootTest(webEnvironment = RANDOM_PORT) is the full-context alternative.", anchor: "Repo Module 9 / Spring Boot testing talk track" },
    { track: "api", type: "mcq", topic: "SPRING BOOT", question: "Your microservice under test calls three downstream microservices. How do you test it in isolation?", options: ["Always test against the full integrated environment", "Stub the downstream HTTP dependencies with WireMock, and use consumer-driven contract tests (Pact / Spring Cloud Contract) to catch breaking API changes", "Mock the entire service under test", "Skip those code paths"], answer: 1, explanation: "WireMock replaces the downstream services with programmable HTTP stubs, so tests are fast and deterministic. Contract tests then verify both sides of each service boundary independently, catching breaking changes before integration environments do.", anchor: "Repo Module 9 / microservices talk track" },
    { track: "api", type: "mcq", topic: "API", question: "Beyond the HTTP status code, what do you validate in an API response?", options: ["Nothing; 200 means it works", "Headers (Content-Type, Location, caching), body correctness against the contract/schema, error-body shape on negative paths, response time SLA, and resulting state (DB or a follow-up GET)", "Only that the body is valid JSON", "The server's IP address"], answer: 1, explanation: "Status is the weakest signal. Validate the contract: headers, every business-relevant field (recompute calculations), schema/required fields, negative-path error bodies, response time, and the side effect—did the resource actually persist?", anchor: "Luxoft Q5 / repo Module 9" },
    { track: "api", type: "mcq", topic: "API", question: "How do you handle rounding and precision when asserting financial calculations in Java tests?", options: ["Compare doubles with ==", "Use BigDecimal (or an explicit tolerance/delta) with a stated rounding mode; never trust double equality for money", "Round everything to integers", "Convert to String and compare"], answer: 1, explanation: "Binary floating point cannot represent most decimal fractions, so 0.1 + 0.2 != 0.3 as doubles. Assert money with BigDecimal.compareTo and the spec's rounding mode (e.g. HALF_UP to 2 decimals), or with an explicit delta. Pair this with boundary, null, and invalid-input negative tests.", anchor: "Luxoft Q8" },
    { track: "api", type: "mcq", topic: "API", question: "What negative and boundary cases matter most for a financial calculation endpoint?", options: ["Only the happy path with round numbers", "Zero and negative quantities, min/max values, nulls and missing fields, malformed JSON, wrong data types, and currency/precision edge amounts — each with the correct 4xx and a useful error body", "Random strings only", "Whatever the developer suggests"], answer: 1, explanation: "Calc engines fail at the edges: zero/negative inputs, overflow-scale values, missing or null fields (400/422 with a field-level error, never a 500), type mismatches, and amounts that stress rounding like 0.005. The error body is part of the contract—assert it.", anchor: "Luxoft Q8 / repo Module 9" },
    { track: "api", type: "mcq", topic: "PERFORMANCE", question: "How would you performance-test a calculation-heavy service with JMeter?", options: ["Open the UI and time it with a stopwatch", "Build a thread group hitting the calc endpoints with realistic parameterized payloads, ramp up load, and assert against SLAs on p90/p95 latency, throughput, and error rate; then push past expected load for stress", "Run the functional suite twice", "JMeter only tests databases"], answer: 1, explanation: "Load test = expected concurrency vs SLA; stress test = increase until it breaks to find the ceiling; soak/endurance = sustained load hunting leaks. Use CSV data sets so every thread sends different calculation inputs, and watch percentiles, not averages.", anchor: "Luxoft Q14" },
    { track: "api", type: "written", topic: "API", question: "What is a POJO request model, and why would you use one instead of a raw JSON string?", coach: "Define POJO, explain serialization, and connect it to maintainability and type safety.", model: "A POJO request model is a simple Java class whose fields represent the API request body. Jackson or REST Assured serializes it to JSON. I would use it for type safety, reusable test data, clearer failures, and easier maintenance when the contract changes. I would use BigDecimal for financial amounts and annotations such as @JsonProperty when Java and JSON names differ.", anchor: "Luxoft API follow-up / d09_api" },
    { track: "api", type: "written", topic: "API", question: "How would you deserialize API JSON into TradeResult POJOs?", coach: "Mention Jackson, a list TypeReference, field mapping, and the financial-amount type.", model: "I would use Jackson directly with ObjectMapper.readValue(json, new TypeReference<List<TradeResult>>() {}) or REST Assured extraction with new TypeRef<List<TradeResult>>() {}. The TradeResult class would have fields, constructors, getters/setters, and BigDecimal for amount. Jackson maps matching JSON names automatically; @JsonProperty handles differences and @JsonIgnoreProperties can handle nonessential fields.", anchor: "Luxoft API follow-up / d09_api" },
    { track: "api", type: "written", topic: "API", question: "How would you call a Spring Boot endpoint with REST Assured?", coach: "Use the given/when/then structure, then add the follow-ups: auth, headers, POJO body, response mapping, and negative cases.", model: "I would configure a reusable request specification for the base URI, authentication, common headers, and logging. The test would use given() to add headers, query parameters, and a POJO body; when() to call get or post; and then() to assert status, content type, headers, response fields, and the business result. I would extract the response as a POJO when later assertions or database reconciliation need typed data.", anchor: "Luxoft API follow-up / d09_api" },
    { track: "api", type: "written", topic: "JAVA", question: "Walk through the financial API coding exercise: calculate settled totals by currency from a List<TradeResult>.", coach: "Talk first: filter statuses, validate IDs and amounts, use BigDecimal, aggregate with a map, then name unit tests.", model: "I would first clarify the rules and validate null records, duplicate IDs, missing currencies, and invalid amounts. Then I would filter to SETTLED records and aggregate amounts in a Map<String, BigDecimal>, using BigDecimal rather than double. I would test multiple currencies, failed and cancelled trades, duplicate IDs, zero or negative amounts, nulls, and precision or rounding boundaries.", anchor: "Luxoft possible technical coding exercise" },
    { track: "api", type: "written", topic: "SPRING BOOT", question: "How would you structure an automation framework for testing Spring Boot services?", coach: "Layers, not tools: project layout, request/client layer, data layer, BDD layer, config, CI. Name what owns what.", model: "A Maven/Java project mirroring the framework I own now, aimed at services instead of pages. A client layer wraps REST Assured request specifications per service—base URI, auth, serialization—so steps never build raw requests, the same role page objects play in UI automation. POJOs model request and response payloads, a validation layer handles JSON assertions and recomputes financial calculations, and a JDBC/SQL helper reconciles against the database. On top sits Cucumber: features describe business flows, step definitions call the client layer, hooks manage environment config and test data. Environments are property-driven, and the whole thing runs headless in Jenkins per push with cucumber and surefire reports published.", anchor: "Luxoft Q2" },
    { track: "api", type: "written", topic: "API", question: "Explain the difference between HTTP 200 and 201, and what you would do if a create endpoint returned the wrong one.", coach: "Cover the semantics of each, the Location header, and the defect conversation—why it matters to clients, not just pedantry.", model: "Both are success codes. 200 OK is generic success with the result in the body—a GET, a PUT update, a search. 201 Created means a new resource now exists because of this request; it is the correct response to a creating POST and should include a Location header with the new resource's URI. If POST /trades returned 200, I would file a defect: API consumers and gateways key off the status semantics, and a missing Location header breaks clients that follow it to the new resource." },
    { track: "api", type: "written", topic: "SPRING BOOT", question: "How would you approach end-to-end API testing for a microservices-based application?", coach: "Layer your answer: per-service tests, stubbed dependencies, contract tests, then a thin end-to-end layer. Name the tools at each layer.", model: "I test each service black-box through its REST API with REST Assured—status codes, headers, and JSON body validation, including recomputing business calculations in large responses. Downstream services get stubbed with WireMock so the tests are deterministic, and consumer-driven contract tests catch breaking changes between services. Database state is verified with SQL. On top of that sits a thin end-to-end suite through the real integration environment for the critical flows only, because full-stack tests are the slowest and flakiest layer. Performance is separate: JMeter thread groups against the same endpoints." },
    { track: "interview", type: "mcq", topic: "PROCESS", question: "What is the difference between retesting and regression testing?", options: ["They are the same activity", "Retesting verifies a specific fixed defect; regression testing verifies the fix (or any change) did not break existing behavior elsewhere", "Regression only happens before release day", "Retesting is automated; regression is always manual"], answer: 1, explanation: "Retesting targets the exact failed case after a fix. Regression sweeps the surrounding functionality for collateral damage—which is why the regression suite is the primary automation investment.", anchor: "Luxoft interview reports / STLC" },
    { track: "interview", type: "written", topic: "VOICE", question: "Tell me about a serious defect you found and how you communicated the release risk.", coach: "Use a real story: how you found it, how you proved impact (severity vs priority), who you told, what data you brought, and what the decision was.", model: "Structure the story: I found a defect in a critical flow late in the cycle, reproduced it reliably, and quantified the impact—which users, which data, how often. I separated severity from priority, brought evidence rather than opinion—reproduction steps, logs, the affected calculation—and raised it to the decision owners with options: fix now, ship with a documented workaround, or hold the release. My job was to make the risk visible and let the business make an informed call; I documented the decision and added a regression test so it could never return silently.", anchor: "Luxoft Q15" },
    { track: "interview", type: "written", topic: "VOICE", question: "How would you answer: Tell me about yourself and your QA responsibilities in 90 seconds?", coach: "Connect your experience to this role: automation scope, validation depth, framework ownership, and the value you create.", model: "I am a QA/SDET professional focused on turning risk into repeatable validation. My work spans UI automation with Selenium, API and data checks, framework patterns, and CI feedback. I focus on reliable signals—stable locators, meaningful waits, clear assertions, and evidence when a failure is real. In this role I would bring that same approach to expanding coverage while keeping the suite maintainable and useful to the team." }
,
    { track: "selenium", type: "mcq", topic: "SELENIUM", question: "What are the components of the Selenium suite today?", options: ["WebDriver, IDE, and Grid", "Only WebDriver", "RC, Core, and Postman", "JMeter and Cucumber"], answer: 0, explanation: "WebDriver drives the browser via each browser's native driver, IDE records/plays back for prototyping, and Grid distributes tests across machines/browsers. Selenium RC is retired—WebDriver replaced its JavaScript-injection approach with native browser automation (the W3C WebDriver protocol in Selenium 4).", anchor: "Infosys Selenium Q2/Q4" },
    { track: "selenium", type: "mcq", topic: "SELENIUM", question: "Which locator is generally fastest, and why?", options: ["XPath, because it is the most powerful", "By.id — browsers optimize document.getElementById, and ids should be unique", "By.linkText", "CSS class name, always"], answer: 1, explanation: "By.id maps to the browser's fastest native lookup and is the most stable when ids are unique and not auto-generated. Practical order of preference: id, name, CSS, then XPath.", anchor: "Infosys Selenium Q6" },
    { track: "selenium", type: "mcq", topic: "SELENIUM", question: "What makes a FluentWait different from a standard WebDriverWait?", options: ["It is an implicit wait", "You explicitly configure the polling interval and which exceptions to ignore while waiting", "It never times out", "It only works on alerts"], answer: 1, explanation: "FluentWait lets you tune withTimeout, pollingEvery, and ignoring(NoSuchElementException.class). WebDriverWait actually extends FluentWait with a default 500ms poll—know that relationship.", anchor: "Infosys Selenium Q10" },
    { track: "selenium", type: "mcq", topic: "SELENIUM", question: "How do you interact with an element inside an iframe?", options: ["Just findElement; frames are transparent", "driver.switchTo().frame(locator/index/name) first, then locate; switchTo().defaultContent() to come back", "Use JavaScriptExecutor only", "Open the frame URL in a new tab"], answer: 1, explanation: "WebDriver scopes lookups to the current browsing context. Switch into the frame (by index, name/id, or WebElement), interact, then defaultContent() to return to the top document (parentFrame() goes up one level).", anchor: "Infosys Selenium Q12" },
    { track: "selenium", type: "mcq", topic: "SELENIUM", question: "A click opens a new window. How do you continue the test there?", options: ["Selenium follows the new window automatically", "Capture getWindowHandle(), loop getWindowHandles(), switchTo().window(theNewHandle), and switch back when done", "Press Alt+Tab via Actions", "Restart the driver"], answer: 1, explanation: "Save the original handle, iterate the handle set to find the new one, and switchTo().window(handle). Selenium 4 also offers driver.switchTo().newWindow(WindowType.TAB) to open one deliberately.", anchor: "Infosys Selenium Q13" },
    { track: "selenium", type: "mcq", topic: "SELENIUM", question: "XPath vs CSS selector — which trade-off is real?", options: ["CSS can traverse to parent elements; XPath cannot", "XPath can traverse UP the DOM and match by text(); CSS is often faster and more readable but only goes down", "XPath only works in Firefox", "They are identical in capability"], answer: 1, explanation: "XPath supports parent/ancestor axes and text() matching—things CSS cannot do. CSS tends to be faster and easier to read, so prefer it until you need XPath's power.", anchor: "Infosys Selenium Q16" },
    { track: "selenium", type: "mcq", topic: "SELENIUM", question: "Absolute vs relative XPath — why does everyone use relative?", options: ["Absolute is not valid syntax anymore", "Absolute (/html/body/div[2]/...) breaks when ANY ancestor changes; relative (//input[@id='user']) anchors on a stable attribute", "Relative is faster to type only", "Absolute cannot find nested elements"], answer: 1, explanation: "An absolute path encodes the entire DOM chain, so any layout change breaks it. A relative XPath anchors on the nearest stable attribute, surviving structural churn.", anchor: "Infosys Selenium Q17" },
    { track: "selenium", type: "mcq", topic: "SELENIUM", question: "How do you perform drag-and-drop or hover actions?", options: ["sendKeys with arrow characters", "The Actions class: new Actions(driver).dragAndDrop(source, target).perform(), or moveToElement() for hover — don't forget perform()", "driver.drag(source, target)", "Only possible with AutoIt"], answer: 1, explanation: "Actions builds composite gestures: dragAndDrop, moveToElement (hover), contextClick (right-click), doubleClick, keyDown chords. The classic bug is forgetting .perform()—nothing executes without it.", anchor: "Infosys Selenium Q19-20" },
    { track: "selenium", type: "mcq", topic: "SELENIUM", question: "How do you capture a screenshot in Selenium?", options: ["driver.snapshot()", "Cast the driver: ((TakesScreenshot) driver).getScreenshotAs(OutputType.FILE), then copy the file into the report", "Print-screen via Robot only", "Screenshots require Selenium Grid"], answer: 1, explanation: "The driver implements TakesScreenshot. In a framework this lives in an ITestListener/JUnit extension that fires on failure automatically, naming the file after the test. WebElement.getScreenshotAs captures a single element.", anchor: "Infosys Selenium Q22" },
    { track: "selenium", type: "mcq", topic: "SELENIUM", question: "How do you select an option from a standard <select> dropdown?", options: ["Click it and type the value blindly", "Wrap it: new Select(element), then selectByVisibleText / selectByValue / selectByIndex", "JavaScriptExecutor is required", "sendKeys always works for any dropdown"], answer: 1, explanation: "The Select class only works on real <select> tags and offers the three selectBy methods plus getOptions/isMultiple. Custom JS dropdowns (divs) need click-then-click with explicit waits instead.", anchor: "Infosys Selenium Q23" },
    { track: "selenium", type: "mcq", topic: "SELENIUM", question: "When is JavaScriptExecutor the right tool?", options: ["As the default for every click, it's faster", "As a deliberate fallback: scrolling into view, reading JS state, or clicking an element the normal API can't reach — while noting it bypasses user-realistic interaction", "Never; it is deprecated", "Only for alerts"], answer: 1, explanation: "((JavascriptExecutor) driver).executeScript(...) escapes WebDriver's user-simulation. Useful for scrollIntoView or stubborn overlays, but a JS click passes even when a real user couldn't click—so it can hide product bugs. Say that trade-off out loud.", anchor: "Infosys Selenium Q24" },
    { track: "java", type: "mcq", topic: "JAVA", question: "Name the four OOP pillars and the one-line meaning of each.", options: ["Compilation, execution, debugging, deployment", "Encapsulation (hide state behind methods), Inheritance (is-a reuse), Polymorphism (one interface, many forms), Abstraction (expose what, hide how)", "Classes, objects, packages, imports", "Speed, safety, syntax, style"], answer: 1, explanation: "Have a framework example ready for each: BasePage encapsulates waits, page classes inherit from it, an overridden method or WebDriver interface reference is polymorphism, and the page-object API abstracts locator details from tests.", anchor: "Infosys Java Q2-6" },
    { track: "java", type: "mcq", topic: "JAVA", question: "Array vs ArrayList — the key differences?", options: ["No difference since Java 8", "Array is fixed-length and holds primitives directly; ArrayList grows dynamically, holds objects (autoboxing for primitives), and has rich methods", "ArrayList is fixed size", "Arrays cannot hold objects"], answer: 1, explanation: "Arrays: fixed size, primitives allowed, .length field. ArrayList: resizable, objects only, .size() method, add/remove/contains. In test code ArrayList (via the List interface) is the usual default.", anchor: "Infosys Java Q7" },
    { track: "java", type: "mcq", topic: "JAVA", question: "List vs Set — when do you reach for each?", options: ["They are interchangeable", "List keeps insertion order and allows duplicates; Set enforces uniqueness — e.g. dedupe check: assert list.size() == new HashSet<>(list).size()", "Set keeps duplicates sorted", "List cannot be iterated"], answer: 1, explanation: "That one-liner—comparing a List's size to the Set built from it—is a classic SDET idiom for asserting no duplicate rows/ids came back from an API or grid.", anchor: "Infosys Java Q8" },
    { track: "java", type: "mcq", topic: "JAVA", question: "final vs finally vs finalize?", options: ["Three spellings of the same keyword", "final = no reassignment/override/extension; finally = always-runs cleanup block after try/catch; finalize = deprecated pre-GC hook", "finally runs only when an exception is thrown", "final makes a class garbage-collected sooner"], answer: 1, explanation: "final is a modifier (constants, unoverridable methods, unextendable classes). finally is the cleanup block—driver.quit() belongs there or in try-with-resources. finalize() was a GC callback, deprecated—say you'd never use it.", anchor: "Infosys Java Q11" },
    { track: "java", type: "mcq", topic: "JAVA", question: "String vs StringBuilder vs StringBuffer?", options: ["All three are immutable", "String is immutable; StringBuilder is a mutable buffer (single-threaded default); StringBuffer is the synchronized, thread-safe, slower variant", "StringBuffer is immutable", "StringBuilder is thread-safe"], answer: 1, explanation: "Immutability means every String concat creates a new object. StringBuilder mutates in place—the loop-concatenation choice. StringBuffer predates it with synchronized methods; mention you'd rarely need it in test code.", anchor: "Infosys Java Q12" },
    { track: "java", type: "mcq", topic: "JAVA", question: "HashMap vs Hashtable?", options: ["Hashtable is the modern replacement for HashMap", "HashMap is unsynchronized and allows one null key; Hashtable is legacy, synchronized, and forbids nulls — use ConcurrentHashMap when you need thread safety", "HashMap cannot store nulls", "They differ only in package name"], answer: 1, explanation: "The senior twist: don't say 'use Hashtable for threads'—say ConcurrentHashMap, which locks at bucket level instead of every method. Hashtable is a legacy class you'd only meet in old code.", anchor: "Infosys Java Q20" },
    { track: "testng-sql", type: "mcq", topic: "TESTNG", question: "In what order do TestNG's Before annotations fire?", options: ["Random order each run", "@BeforeSuite → @BeforeTest → @BeforeClass → @BeforeMethod (After* unwinds in reverse)", "@BeforeMethod always first", "Alphabetical order"], answer: 1, explanation: "Outside-in: suite, then <test> tag, then class, then each method. @BeforeTest belongs to the testng.xml <test> block—not to each @Test method, which is the classic trap in this question.", anchor: "Infosys TestNG Q2-3" },
    { track: "testng-sql", type: "mcq", topic: "TESTNG", question: "What do priority and dependsOnMethods do in TestNG?", options: ["Both randomize execution", "priority orders independent tests (lower runs first); dependsOnMethods declares a real dependency — the dependent test is SKIPPED, not failed, if the prerequisite fails", "priority makes tests run in parallel", "dependsOnMethods retries failures"], answer: 1, explanation: "priority is ordering only. dependsOnMethods encodes a genuine prerequisite (login before checkout) and skips downstream tests when it breaks—keeping the report honest about one root cause instead of a cascade of failures.", anchor: "Infosys TestNG Q4-5" },
    { track: "testng-sql", type: "mcq", topic: "TESTNG", question: "How do you re-run only the failed tests after a TestNG run?", options: ["Delete the passed tests", "Run the auto-generated testng-failed.xml from test-output, or wire an IRetryAnalyzer for automatic in-run retries", "TestNG cannot do this", "Rename the failing methods"], answer: 1, explanation: "TestNG writes testng-failed.xml after every suite run containing only the failures. IRetryAnalyzer is the in-run alternative—mention retries should be a diagnostic aid, not a flakiness blanket.", anchor: "Infosys TestNG Q7" },
    { track: "testng-sql", type: "mcq", topic: "TESTNG", question: "What is grouping in TestNG for?", options: ["Formatting the HTML report", "Tagging tests with groups = {\"smoke\"} and selecting them in testng.xml <include> — slicing one suite into smoke/regression/api runs without new classes", "Grouping browsers", "It only works with DataProviders"], answer: 1, explanation: "Groups are TestNG's answer to Cucumber tags: cross-cutting labels selected at suite level. A method can belong to several groups, and CI jobs pick the slice they need.", anchor: "Infosys TestNG Q8" },
    { track: "framework", type: "mcq", topic: "FRAMEWORK", question: "What is a hybrid framework?", options: ["A framework that tests mobile and web", "One combining multiple styles — e.g. Page Object structure with data-driven inputs and keyword/BDD layers — which is what most real frameworks are", "Half manual, half automated", "A framework with two programming languages"], answer: 1, explanation: "Interviewers want you to map the textbook labels onto YOUR framework: POM for structure, DataProviders/CSV for data-driven, Cucumber as the behavior layer. Say 'mine is hybrid' and name the ingredients.", anchor: "Infosys Framework Q4-6" },
    { track: "framework", type: "mcq", topic: "FRAMEWORK", question: "What roles do Maven play in your automation project?", options: ["It is only a downloader", "Dependency management (pom.xml pulls Selenium/TestNG versions), standard lifecycle (compile/test), and Surefire runs the suite — the same command works locally and in CI", "It replaces Jenkins", "It writes the tests"], answer: 1, explanation: "pom.xml declares versions once, transitively resolves libraries, and mvn test compiles then executes via the Surefire plugin. Profiles switch configurations (e.g. a parallel TestNG suite) from the command line.", anchor: "Infosys Framework Q12" },
    { track: "framework", type: "mcq", topic: "FRAMEWORK", question: "How do you run a specific test from the command line?", options: ["You must use the IDE", "mvn test -Dtest=LoginTests#loginWithValidCredentials, plus -D system properties for runtime switches like -Dheadless=true", "java TestFile.java", "mvn deploy"], answer: 1, explanation: "-Dtest targets a class or single method; system properties feed runtime configuration the framework reads (headless, environment, browser). This is also exactly what the CI pipeline invokes.", anchor: "Infosys Framework Q15" },
    { track: "api", type: "mcq", topic: "API", question: "GET vs POST — the differences that matter?", options: ["GET is newer than POST", "GET reads — parameters in the URL, no body, safe/idempotent/cacheable; POST submits a body to create or process — not idempotent, never cacheable by default", "POST cannot carry JSON", "GET is more secure for passwords"], answer: 1, explanation: "Also say the security angle: sensitive data never goes in a GET query string (it lands in logs and history). And the testing angle: repeating a GET is free; repeating a POST may create duplicates.", anchor: "Infosys API Q3" },
    { track: "api", type: "mcq", topic: "API", question: "How does token-based authentication work in API testing?", options: ["Send the password on every request", "Authenticate once to receive a token (often a JWT), send it as Authorization: Bearer <token> on each call, and test expiry/invalid/missing-token paths", "Tokens are only for UIs", "Base64-encode the URL"], answer: 1, explanation: "The framework logs in once in a hook, stores the token, and injects the Authorization header into every request spec. Negative tests: expired token (401), tampered token (401), valid token wrong role (403).", anchor: "Infosys API Q9-10" },
    { track: "testng-sql", type: "mcq", topic: "SQL", question: "Primary key vs foreign key?", options: ["Both allow duplicates", "Primary key uniquely identifies a row (no nulls, no duplicates); a foreign key references another table's primary key, enforcing referential integrity", "Foreign keys must be unique", "Primary keys can be null once"], answer: 1, explanation: "Testing angle: referential integrity is checkable—orphaned child rows (a trade pointing at a missing account) are a data-layer defect an SDET can catch with one LEFT JOIN ... WHERE parent IS NULL query.", anchor: "Infosys SQL Q2-3" },
    { track: "testng-sql", type: "mcq", topic: "SQL", question: "What is an index, and what is the trade-off?", options: ["A backup of the table", "A lookup structure that speeds up reads on the indexed columns, at the cost of slower writes and extra storage", "It makes writes faster", "A synonym for primary key"], answer: 1, explanation: "Like a book index: fast lookup without scanning every page, but every insert/update must also maintain the index. Related follow-up: normalization organizes tables to remove redundancy (1NF/2NF/3NF).", anchor: "Infosys SQL Q9-10" },
    { track: "interview", type: "mcq", topic: "PROCESS", question: "Severity vs priority — and give the classic mismatch examples.", options: ["They are synonyms", "Severity = technical impact (QA assesses); priority = business urgency of fixing (product decides). Crash in a dead feature: high severity, low priority. Typo in the company logo: low severity, high priority", "Priority is always higher than severity", "Developers set both"], answer: 1, explanation: "Always give both cross-examples—that is what proves you understand the distinction rather than reciting it.", anchor: "Infosys Manual Q5" },
    { track: "interview", type: "mcq", topic: "PROCESS", question: "Smoke vs sanity testing?", options: ["Identical activities", "Smoke: broad-and-shallow check that a new build's critical paths work at all (gate before deeper testing); sanity: narrow-and-deep check that a specific fix or change behaves before full regression", "Sanity is always automated; smoke never is", "Smoke tests only run in production"], answer: 1, explanation: "Wide-vs-deep is the memorable frame. Smoke answers 'is this build testable?'; sanity answers 'did this specific change land correctly?'", anchor: "Infosys Manual Q7-8" },
    { track: "interview", type: "mcq", topic: "PROCESS", question: "Walk through the bug life cycle.", options: ["Found → fixed, nothing else", "New → Assigned → Open/In-progress → Fixed → Retest → Verified → Closed, with branches for Rejected, Duplicate, Deferred, and Reopened when the retest fails", "Bugs skip straight to Closed", "The tester closes bugs without retesting"], answer: 1, explanation: "The states matter less than who owns each transition: QA verifies the fix before Closed, and Reopened is QA's lever when a fix doesn't hold. In JIRA these are workflow statuses.", anchor: "Infosys Manual Q4" },
    { track: "java", type: "mcq", topic: "JAVA", question: "What do the static and this keywords mean in Java?", options: ["static means unchangeable; this creates an object", "static members belong to the class, not any instance (shared across objects, no this available); this refers to the current instance — disambiguating fields from parameters or chaining constructors", "this only works in main()", "They are interchangeable"], answer: 1, explanation: "Framework examples to cite: a static WebDriverWait utility or By constants belong to the class; this.driver = driver in a page object constructor is the everyday use of this. Bonus: static methods can't touch instance fields — that's why main() can't use this.", anchor: "Barclays R1 Q7" },
    { track: "selenium", type: "mcq", topic: "SELENIUM", question: "How should Selenium scripts handle exceptions?", options: ["Wrap everything in one try/catch that swallows all exceptions", "Catch only where you can add value (retry a stale element, attach a screenshot, wrap in a clearer message); otherwise let the test FAIL loudly — a swallowed exception is a fake green", "Use System.exit(1) in every catch block", "Selenium never throws exceptions"], answer: 1, explanation: "Know the common ones and their meaning: NoSuchElement (locator/sync), StaleElementReference (DOM refresh), TimeoutException (wait expired), ElementClickIntercepted (overlay). Handle at the framework layer — a listener that screenshots on failure — not with per-line try/catch noise.", anchor: "Barclays R1 Q9" },
    { track: "selenium", type: "mcq", topic: "SELENIUM", question: "How do you run cross-browser tests?", options: ["Rewrite the suite per browser", "Parameterize browser choice (system property or testng.xml parameter) into a driver factory, and scale out via Selenium Grid or a cloud provider — same tests, different capabilities", "Only Chrome can be automated", "Install every browser on your laptop and run sequentially forever"], answer: 1, explanation: "The driver factory reads the browser parameter and returns the right driver (WebDriverManager handles binaries). Grid/cloud (Selenium Grid, Sauce Labs, BrowserStack) runs the same suite across browser/OS combinations in parallel — pairs with the ThreadLocal driver answer.", anchor: "Barclays R2 Q10" },
    { track: "framework", type: "mcq", topic: "FRAMEWORK", question: "How do you manage test data and environment configurations?", options: ["Hard-code them in each test", "Externalize both: environment settings in property/YAML files or CI variables selected by a runtime flag (-Denv=qa); test data in DataProviders, CSV/Excel/JSON, or builders — never hard-coded in test logic", "Keep them in the developer's head", "One shared production account for everything"], answer: 1, explanation: "The seniority markers: secrets come from the CI vault (never committed), tests create-or-clean their own data where possible for independence, and the same suite runs against any environment by switching one flag.", anchor: "Barclays R2 Q2 / Infosys Framework Q8" },
    { track: "framework", type: "mcq", topic: "FRAMEWORK", question: "What practices keep automation scripts maintainable?", options: ["Copy-paste working tests and tweak them", "DRY through page objects and shared utilities, explicit waits centralized in a base class, meaningful names, small independent tests, one logical assertion focus, code review for test code, and deleting dead tests", "Longer tests that cover everything at once", "Comments explaining every line"], answer: 1, explanation: "The theme is: treat test code like production code. Locator changes touch one file, tests don't depend on each other's state, and the suite stays fast enough that people actually run it.", anchor: "Barclays R2 Q3" },
    { track: "framework", type: "mcq", topic: "FRAMEWORK", question: "Describe a standard Git workflow for automation code.", options: ["Everyone commits straight to main", "Feature branches off main, small commits, push and open a pull request, code review + CI green as the merge gate, then delete the branch — same discipline as application code", "Email zip files of the framework", "One permanent personal branch per engineer, merged yearly"], answer: 1, explanation: "Name the flow you actually use: branch per JIRA ticket, PR into main (or develop in gitflow shops), review plus the pipeline passing as the gate. Bonus points: automation code reviews check for dead assertions and flaky patterns, not just style.", anchor: "Barclays R2 Q7" },
    { track: "framework", type: "written", topic: "FRAMEWORK", question: "What common challenges have you faced in automation, and how did you resolve them?", coach: "Pick 2-3 real ones: synchronization/flakiness, dynamic locators, test data, environment instability. For each: the symptom, the root cause, the fix, and what you standardized so it stayed fixed.", model: "The recurring ones: synchronization — intermittent failures that turned out to be timing; I standardized explicit waits in a base class and banned Thread.sleep in review. Dynamic locators — auto-generated ids breaking tests; I moved to stable attributes and relative XPath anchored on text or data-test attributes, and pushed developers to add test ids. Test data collisions in parallel runs — tests sharing accounts; I made each test create or reserve its own data. And environment flakiness — I separated 'app is down' from 'test failed' with a health check before the suite, so red means defect, not noise. The pattern in all of them: fix the class of problem in the framework, not the one test.", anchor: "Barclays R2 Q9" }
];

const codingDrills = [
    { category: "LABCORP-STYLE", title: "Print every letter of a name", prompt: "Given a name, write Java code that visits and prints each letter in order. Start with the input \"PETER\" and make the solution work for any name.", listening: "a loop, charAt or a character array, and a clear explanation of the index boundary", hint: "A String has a length and a zero-based character at each index.", solution: "String name = \"PETER\";\nfor (int i = 0; i < name.length(); i++) {\n    System.out.println(name.charAt(i));\n}" },
    { category: "DELOITTE-STYLE", title: "Reverse letters, preserve whitespace", prompt: "Write Java code to reverse the non-whitespace characters in a string while keeping every whitespace character in its original position. Example: \"a b c\" → \"c b a\".", listening: "separating whitespace from content, preserving positions, and calling out an empty or all-whitespace case", hint: "First collect non-whitespace characters. Walk the original string again and replace only non-whitespace positions from the reversed collection.", solution: "String input = \"a b c\";\nStringBuilder letters = new StringBuilder();\nfor (char c : input.toCharArray()) {\n    if (!Character.isWhitespace(c)) letters.append(c);\n}\nletters.reverse();\nStringBuilder result = new StringBuilder();\nint index = 0;\nfor (char c : input.toCharArray()) {\n    result.append(Character.isWhitespace(c) ? c : letters.charAt(index++));\n}\nSystem.out.println(result);" },
    { category: "LUXOFT-STYLE API", title: "Calculate settled totals by currency", prompt: "Given a List<TradeResult> with tradeId, status, currency, and BigDecimal amount, return a Map<String, BigDecimal> of totals for SETTLED trades. Reject duplicate IDs and invalid records. Explain your tests.", listening: "filtering by status, BigDecimal aggregation, validation policy, and tests for multiple currencies, duplicates, nulls, and precision", hint: "Use a Set for seen trade IDs and a Map<String, BigDecimal> for totals. State whether invalid records are rejected or collected as validation errors.", solution: "static Map<String, BigDecimal> calculateSettledTotals(List<TradeResult> results) {\n    Set<String> seenIds = new HashSet<>();\n    Map<String, BigDecimal> totals = new LinkedHashMap<>();\n    for (TradeResult trade : results) {\n        if (trade == null || trade.getTradeId() == null ||\n                !seenIds.add(trade.getTradeId())) {\n            throw new IllegalArgumentException(\"Invalid or duplicate trade\");\n        }\n        if (\"SETTLED\".equals(trade.getStatus())) {\n            if (trade.getCurrency() == null || trade.getAmount() == null ||\n                    trade.getAmount().signum() < 0) {\n                throw new IllegalArgumentException(\"Invalid settled trade\");\n            }\n            totals.merge(trade.getCurrency(), trade.getAmount(), BigDecimal::add);\n        }\n    }\n    return totals;\n}" },
    { category: "JAVA CORE", title: "Find duplicate characters", prompt: "Given a string, print each character that appears more than once. Explain whether you want to print a duplicate once or every repeated occurrence.", listening: "a Set or Map, an explicit policy for output, and case-sensitivity as a stated assumption", hint: "A frequency map answers how many times each character occurs. A LinkedHashMap can preserve first-seen order.", solution: "String input = \"selenium\";\nMap<Character, Integer> counts = new LinkedHashMap<>();\nfor (char c : input.toCharArray()) {\n    counts.put(c, counts.getOrDefault(c, 0) + 1);\n}\ncounts.forEach((character, count) -> {\n    if (count > 1) System.out.println(character);\n});" },
    { category: "JAVA CORE", title: "Check for a palindrome", prompt: "Write a method that returns true when a string reads the same forward and backward. State whether you ignore case or whitespace.", listening: "normalization assumptions, two-pointer logic or a reversed comparison, and a useful edge case", hint: "Compare the first and last characters, then move both pointers toward the middle.", solution: "static boolean isPalindrome(String value) {\n    String input = value.replaceAll(\"\\\\s+\", \"\").toLowerCase();\n    int left = 0, right = input.length() - 1;\n    while (left < right) {\n        if (input.charAt(left++) != input.charAt(right--)) return false;\n    }\n    return true;\n}" },
    { category: "DELOITTE-STYLE", title: "Find the second-largest salary", prompt: "Write a SQL query that returns the second-largest distinct salary from an employee table. Explain what happens if there is no second value.", listening: "distinctness, a clear subquery or ranking approach, and the empty-result edge case", hint: "Find the maximum salary below the overall maximum salary.", solution: "SELECT MAX(salary) AS second_highest\nFROM employees\nWHERE salary < (SELECT MAX(salary) FROM employees);" },
    { category: "JAVA CORE", title: "Reverse a string", prompt: "Write a Java method to reverse a string without changing the original input object. Mention the simplest library-backed solution and how you would do it manually.", listening: "String immutability, StringBuilder, and one sentence about a two-pointer or loop alternative", hint: "StringBuilder has a reverse operation and returns a new String when you call toString().", solution: "static String reverse(String input) {\n    return new StringBuilder(input).reverse().toString();\n}" }
];

const state = { track: "all", questions: [], index: 0, correct: 0, answered: false, selected: null, correctIndex: null, codingIndex: 0 };
const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => Array.from(document.querySelectorAll(selector));

function shuffle(items) { return [...items].sort(() => Math.random() - 0.5); }
// Question data contains literal tags like <select> and Map<String,String>; escape before innerHTML.
function esc(text) { return String(text).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;"); }
function todayKey() { return new Date().toISOString().slice(0, 10); }
function readStats() {
    try { return JSON.parse(localStorage.getItem("sdetFieldTestStats")) || { streak: 0, best: null, sessions: 0, lastDate: null }; }
    catch { return { streak: 0, best: null, sessions: 0, lastDate: null }; }
}
function writeStats(stats) { localStorage.setItem("sdetFieldTestStats", JSON.stringify(stats)); }
function renderStats() {
    const stats = readStats();
    $("#streak-stat").textContent = (stats.streak || 0) + " day" + (stats.streak === 1 ? "" : "s");
    $("#best-stat").textContent = stats.best === null ? "—" : stats.best + "/" + (stats.bestTotal || 10);
    $("#sessions-stat").textContent = stats.sessions || 0;
}
function updateTrackLabel() {
    const button = document.querySelector("[data-track=\"" + state.track + "\"]");
    $("#track-label").textContent = (state.track === "all" ? "MIXED SIGNAL" : button.textContent.replace("↗", "").trim()).toUpperCase();
}
function startSession() {
    // Written prompts live in their own module; every other track is MCQ-only.
    const pool = state.track === "written"
        ? questionBank.filter((item) => item.type === "written")
        : questionBank.filter((item) => item.type === "mcq" && (state.track === "all" || item.track === state.track));
    // No repeats: sample without replacement, capped at 20 (or the whole pool if smaller).
    state.questions = shuffle(pool).slice(0, Math.min(20, pool.length));
    state.index = 0; state.correct = 0; state.answered = false; state.selected = null;
    updateTrackLabel(); renderQuestion();
}
function renderQuestion() {
    const question = state.questions[state.index];
    if (!question) return showComplete();
    state.answered = false; state.selected = null;
    const current = state.index + 1;
    $("#question-count").textContent = "QUESTION " + String(current).padStart(2, "0") + " / " + state.questions.length;
    $("#question-topic").textContent = question.topic;
    $("#progress-fill").style.width = (current / state.questions.length) * 100 + "%";
    const title = "<h3><span class=\"q-number\">" + (question.type === "written" ? "WRITE YOUR ANSWER" : "CHOOSE THE BEST ANSWER") + "</span>" + esc(question.question) + "</h3>";
    const view = $("#question-view");
    if (question.type === "written") {
        view.innerHTML = "<div class=\"question-frame written\">" + title + "<textarea class=\"written-answer\" id=\"written-answer\" placeholder=\"Say it out loud first, then capture your answer here...\"></textarea><p class=\"coach-prompt\">" + esc(question.coach) + "</p><div class=\"question-foot\"><span></span><div class=\"question-actions\"><button class=\"text-button\" id=\"reveal-written\" type=\"button\">Reveal coach note <span>↗</span></button><button class=\"button button-primary\" id=\"next-question\" type=\"button\" disabled>Log answer <span>→</span></button></div></div><div id=\"written-feedback\"></div></div>";
        $("#written-answer").addEventListener("input", (event) => { $("#next-question").disabled = !event.target.value.trim(); });
        $("#reveal-written").addEventListener("click", () => { $("#written-feedback").innerHTML = "<div class=\"feedback\"><strong>Coach note:</strong> " + esc(question.model) + "</div>"; });
        $("#next-question").addEventListener("click", () => {
            if (!$("#written-answer").value.trim()) return;
            state.index += 1;
            renderQuestion();
        });
    } else {
        // Shuffle the answer positions every time so the correct letter can't be memorized.
        const order = shuffle(question.options.map((_, index) => index));
        state.correctIndex = order.indexOf(question.answer);
        const options = order.map((originalIndex, index) => "<button class=\"option\" data-option=\"" + index + "\" type=\"button\"><span class=\"option-letter\">" + String.fromCharCode(65 + index) + "</span><span>" + esc(question.options[originalIndex]) + "</span></button>").join("");
        view.innerHTML = "<div class=\"question-frame\">" + title + "<div class=\"answer-options\">" + options + "</div><div class=\"question-foot\"><span class=\"anchor-note\">Source signal: " + esc(question.anchor) + "</span><div class=\"question-actions\"><button class=\"text-button\" id=\"skip-question\" type=\"button\">Skip for now</button><button class=\"button button-primary\" id=\"check-answer\" type=\"button\" disabled>Check answer <span>→</span></button></div></div><div id=\"answer-feedback\"></div></div>";
        $$(".option").forEach((button) => button.addEventListener("click", () => {
            if (state.answered) return;
            state.selected = Number(button.dataset.option);
            $$(".option").forEach((candidate) => candidate.classList.toggle("selected", candidate === button));
            $("#check-answer").disabled = false;
        }));
        $("#check-answer").addEventListener("click", checkAnswer);
        $("#skip-question").addEventListener("click", () => { state.index += 1; renderQuestion(); });
    }
}
function checkAnswer() {
    if (state.selected === null || state.answered) return;
    const question = state.questions[state.index];
    state.answered = true;
    const correct = state.selected === state.correctIndex;
    if (correct) state.correct += 1;
    $$(".option").forEach((button, index) => {
        button.disabled = true;
        if (index === state.correctIndex) button.classList.add("correct");
        if (index === state.selected && !correct) button.classList.add("incorrect");
    });
    $("#answer-feedback").innerHTML = "<div class=\"feedback " + (correct ? "is-correct" : "") + "\"><strong>" + (correct ? "Correct." : "Not quite.") + "</strong> " + esc(question.explanation) + "</div><div class=\"question-actions next-action\"><button class=\"button button-primary\" id=\"next-question\" type=\"button\">" + (state.index === state.questions.length - 1 ? "See score" : "Next question") + " <span>→</span></button></div>";
    $("#check-answer").remove(); $("#skip-question").remove();
    $("#next-question").addEventListener("click", () => { state.index += 1; renderQuestion(); });
}
function showComplete() {
    const stats = readStats(), score = state.correct, today = todayKey(), yesterday = new Date(Date.now() - 86400000).toISOString().slice(0, 10);
    stats.streak = stats.lastDate === yesterday ? (stats.streak || 0) + 1 : stats.lastDate === today ? (stats.streak || 1) : 1;
    stats.lastDate = today; stats.sessions = (stats.sessions || 0) + 1;
    const isWritten = state.track === "written";
    if (!isWritten) {
        // Best score resets when the session length changes (old 10-question bests don't compare).
        if (stats.best === null || (stats.bestTotal || 10) !== state.questions.length) {
            stats.best = score; stats.bestTotal = state.questions.length;
        } else {
            stats.best = Math.max(stats.best, score);
        }
    }
    writeStats(stats); renderStats();
    $("#question-count").textContent = "SESSION COMPLETE"; $("#question-topic").textContent = "LOGGED"; $("#progress-fill").style.width = "100%";
    $("#question-view").innerHTML = "<div class=\"complete-state\"><div class=\"score-stamp\">" + (isWritten ? state.questions.length + " LOGGED" : score + "/" + state.questions.length) + "</div><h3>You showed up.<br><em>Now sharpen the misses.</em></h3><p>Review the answer notes, then run the same track again tomorrow. Your job is not to recognize the answer—it is to produce it cleanly under pressure.</p><div><button class=\"button button-primary\" id=\"restart-session\" type=\"button\">Run another session <span>↗</span></button></div></div>";
    $("#restart-session").addEventListener("click", startSession);
}
function renderCoding() {
    const drill = codingDrills[state.codingIndex];
    $("#coding-category").textContent = drill.category; $("#coding-number").textContent = "DRILL " + String(state.codingIndex + 1).padStart(2, "0");
    $("#coding-title").textContent = drill.title; $("#coding-prompt-text").textContent = drill.prompt; $("#coding-listening").textContent = drill.listening;
    $("#code-answer").value = ""; $("#hint-box").hidden = true; $("#solution-box").hidden = true; $("#hint-box").textContent = drill.hint; $("#solution-box").textContent = drill.solution;
}
$$(".track-button").forEach((button) => button.addEventListener("click", () => {
    state.track = button.dataset.track; $$(".track-button").forEach((item) => item.classList.toggle("is-active", item === button)); startSession();
}));
$("#new-session").addEventListener("click", startSession);
$("#next-coding").addEventListener("click", () => { state.codingIndex = (state.codingIndex + 1) % codingDrills.length; renderCoding(); });
$("#show-hint").addEventListener("click", () => { $("#hint-box").hidden = !$("#hint-box").hidden; });
$("#show-solution").addEventListener("click", () => { $("#solution-box").hidden = !$("#solution-box").hidden; });
$("#date-readout").textContent = new Intl.DateTimeFormat("en-US", { weekday: "short", month: "short", day: "numeric", year: "numeric" }).format(new Date());
renderStats(); renderCoding(); startSession();
